spring:
  application:
    name: oauth2-server
  # 改成代码配置
  #security:
  #  user:
  #    # 账号
  #    name: root
  #    # 密码
  #    password: 123456

server:
  port: 58084
  servlet:
    context-path: /oauth2-server